quiz:
    path:     /
    defaults: { _controller: "VacilosQuizBundle:Quiz:index" }

quiz_show:
    path:     /{id}/show
    defaults: { _controller: "VacilosQuizBundle:Quiz:show" }

quiz_new:
    path:     /new
    defaults: { _controller: "VacilosQuizBundle:Quiz:new" }

quiz_create:
    path:     /create
    defaults: { _controller: "VacilosQuizBundle:Quiz:create" }
    methods:  POST

quiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "VacilosQuizBundle:Quiz:edit" }

quiz_update:
    path:     /{id}/update
    defaults: { _controller: "VacilosQuizBundle:Quiz:update" }
    methods:  [POST, PUT]

quiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "VacilosQuizBundle:Quiz:delete" }
    methods:  [POST, DELETE]
